name: Update the date in the humans.txt file

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-humans-txt:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the workflow to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update humans.txt date
        run: |
          current_date=$(date +'%Y-%m-%d')
          sed -i "s/Last updated: .*/Last updated: $current_date/" public/humans.txt

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update date in humans.txt"
          branch: main
          file_pattern: "public/humans.txt"
